-- Add AI artwork processing URL columns to order_items table
-- This migration adds support for storing print-ready and web preview URLs
-- generated by the AI artwork processor

-- Add columns for AI artwork processing URLs
ALTER TABLE order_items 
ADD COLUMN IF NOT EXISTS print_ready_url TEXT,
ADD COLUMN IF NOT EXISTS web_preview_url TEXT,
ADD COLUMN IF NOT EXISTS artwork_metadata_url TEXT;

-- Add indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_order_items_print_ready_url ON order_items(print_ready_url);
CREATE INDEX IF NOT EXISTS idx_order_items_web_preview_url ON order_items(web_preview_url);

-- Add comments for documentation
COMMENT ON COLUMN order_items.print_ready_url IS 'URL to the print-ready file (PDF/TIFF) with exact dimensions and no overlays';
COMMENT ON COLUMN order_items.web_preview_url IS 'URL to the web preview file (JPG) with overlays for customer viewing';
COMMENT ON COLUMN order_items.artwork_metadata_url IS 'URL to the JSON metadata file containing processing details';
