import { useEffect, useState } from 'react';
import { CircleDollarSign, FileDown, Link2, ShoppingBag } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { downloadOutboundOrdersCsv, getOutboundAnalytics } from '@/lib/outboundSales';

interface Order { id:string;sourceOrderId:string;businessName:string;attributionMethod:string;attributionConfidence:number;attributedRevenueCents:number;currency:string;sourceOrderStatus:string;orderedAt:string|null;attributedAt:string;campaignName:string|null }
interface OrdersData { orders:Order[];summary:{orderCount:number;revenueCents:number;pendingCandidates:number};limit:number;offset:number }
const money=(cents:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(cents/100);

export default function SalesOrders(){
  const [data,setData]=useState<OrdersData|null>(null);const [schemaReady,setSchemaReady]=useState(false);
  useEffect(()=>{const controller=new AbortController();void getOutboundAnalytics<OrdersData>('orders',{limit:250,signal:controller.signal}).then((result)=>{setSchemaReady(result.schemaReady);setData(result.data);}).catch(()=>null);return()=>controller.abort();},[]);
  return <div className="space-y-6"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-2xl font-black text-slate-950">Orders & Revenue Generated</h2><p className="mt-1 text-sm text-slate-500">Attribution reads paid, non-test orders and writes only outbound records. Checkout, payment, and order rows are never changed.</p></div><Button variant="outline" onClick={()=>void downloadOutboundOrdersCsv()} disabled={!schemaReady}><FileDown className="mr-2 h-4 w-4" />Export orders CSV</Button></div></section><section className="grid gap-4 sm:grid-cols-3">{[['Attributed orders',data?.summary.orderCount??0,ShoppingBag],['Revenue generated',money(data?.summary.revenueCents??0),CircleDollarSign],['Pending review',data?.summary.pendingCandidates??0,Link2]].map(([label,value,Icon])=>{const ItemIcon=Icon as typeof ShoppingBag;return <div key={String(label)} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><ItemIcon className="h-5 w-5 text-[#18448D]"/><p className="mt-3 text-xs font-black uppercase tracking-wide text-slate-500">{label}</p><p className="mt-1 text-2xl font-black text-slate-950">{value}</p></div>;})}</section>{!schemaReady&&<div className="rounded-xl border border-amber-200 bg-amber-50 p-5 text-amber-900">Attribution migration is not present. Legacy orders remain untouched and attribution is inactive.</div>}<div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white shadow-sm"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500"><tr><th className="p-4">Business</th><th className="p-4">Order</th><th className="p-4">Method</th><th className="p-4">Revenue</th><th className="p-4">Attributed</th></tr></thead><tbody>{data?.orders.map((order)=><tr key={order.id} className="border-t border-slate-100"><td className="p-4 font-bold text-slate-900">{order.businessName}<div className="text-xs font-normal text-slate-500">{order.campaignName||'No campaign'}</div></td><td className="p-4 font-mono text-xs">{order.sourceOrderId}</td><td className="p-4"><Badge variant="outline">{order.attributionMethod.replace(/_/g,' ')}</Badge><div className="mt-1 text-xs text-slate-500">{Math.round(order.attributionConfidence*100)}% confidence</div></td><td className="p-4 font-black">{money(order.attributedRevenueCents)}</td><td className="p-4 text-slate-500">{new Date(order.attributedAt).toLocaleDateString()}</td></tr>)}</tbody></table>{schemaReady&&!data?.orders.length&&<div className="p-12 text-center text-slate-500">No paid orders have been attributed.</div>}</div></div>;
}
